import { ArrowLeftIcon } from "@heroicons/react/outline";
import {
  collection,
  doc,
  onSnapshot,
  orderBy,
  query,
} from "firebase/firestore";
import { getProviders, getSession, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import { useRecoilState } from "recoil";
import { modalState } from "../atoms/modalAtom";
import Login from "../components/Login";
import Modal from "../components/Modal";
import Post from "../components/Post";
import { db } from "../firebase";
import Comment from "../components/Comment";
import trendingResults from "../utils/trend";
import followResults from "../utils/follow";
import Widgets from "../components/Widgets";
import Sidebar from "../components/Sidebar";

const PostPage = ({ providers }) => {
  const { data: session } = useSession();
  const [post, setPost] = useState();
  const [comments, setComments] = useState([]);
  const [isOpen, setIsOpen] = useRecoilState(modalState);
  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
    onSnapshot(doc(db, "posts", id), (snapshot) => {
      setPost(snapshot.data());
    });
  }, [id]);

  useEffect(
    () =>
      onSnapshot(
        query(
          collection(db, "posts", id, "comments"),
          orderBy("timestamp", "desc")
        ),
        (snapshot) => setComments(snapshot.docs)
      ),
    [id]
  );

  if (!session) return <Login providers={providers} />;

  return (
    <div className="">
      <Head>
        <title>
          {post?.username} on twitter: `&quot;`{post?.text}`&quot;`
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/2.png" />
      </Head>
      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto">
        <Sidebar />
        <div className="flex-grow border-l border-r border-gray-700 max-w-2xl sm:ml-[73px] xl:ml-[370px]">
          <div className="flex items-center px-1.5 py-2 border-b border-gray-700 text-[#d9d9d9] font-semibold text-xl gap-x-4 sticky top-0 z-50 bg-black">
            <div
              className="hoverAnimation w-9 h-9 flex items-center justify-center xl:px-0"
              onClick={() => router.push("/")}
            >
              <ArrowLeftIcon className="text-white h-5" />
            </div>
            Tweet
          </div>
          <Post id={id} post={post} postPage />
          {comments.length > 0 &&
            comments.map((comment) => (
              <Comment
                key={comment.id}
                id={comment.id}
                comment={comment.data()}
              />
            ))}
        </div>
        <Widgets
          trendingResults={trendingResults}
          followResults={followResults}
        />
        {isOpen && <Modal />}
      </main>
    </div>
  );
};

export default PostPage;
export async function getServerSideProps(context) {
  const trendingResults = await fetch(
    "https://twitter154.p.rapidapi.com/user/followers"
  ).then((res) => res.json());
  const followResults = await fetch(
    "https://twitter154.p.rapidapi.com/user/followers"
  ).then((res) => res.json());
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      trendingResults,
      followResults,
      providers,
      session,
    },
  };
}
